name: maspipeline
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - scikit-learn
  - astropy=5.3
  - ccdproc=2.4
  - scipy=1.10.1
  - photutils=2.3
  - pip
  - pip:
    - -e .