[project]
name = "mas_skipper_pipeline"
version = "2.0.1"
description = "Imaging reduction package for the MAS Skipper CCD"
authors = [
    {name = "Christopher Montalbán", email = "christopher.montalban@gmail.cl"}
]
requires-python = ">=3.8"
license = {text = "MIT"}  # O tu licencia
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# ALL your project's runtime dependencies go here, directly under [project]
dependencies = [
    "numpy",
    "matplotlib",
    "scikit-learn",
    "astropy>=5.2,<6.0",
    "ccdproc>=2.4",
    "scipy>=1.11,<1.14",
    "photutils>=2.3"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mas_skipper"]

[project.scripts]
mas-ccd = "mas_skipper.imaging.mas_ccd:main"
mas-phot = "mas_skipper.photometry.mas_phot:main"
